name: kurokos
version: 0.0.0
synopsis: A simple game framework
description: See README at <https://github.com/masatoko/kurokos#README>
maintainer: Masato Kobayashi <masatokodo@gmail.com>
license: MIT
github: masatoko/kurokos
category: Game Engine

ghc-options:
  - -Wall
  - -fno-warn-unused-do-bind

flags:
  demo:
    description: Build demo executable
    manual: False
    default: False

dependencies:
  - base >= 4.7 && < 5
  - sdl2 >= 2.2.0
  - sdl2-ttf >= 2.0.0
  - sdl2-image
  - kurokos-gfx
  - kurokos-ui
  - kurokos-sdl2-gfx
  - kurokos-rpn
  - kurokos-asset
  - kurokos-asset-raw
  - kurokos-asset-sdl2
  - transformers-base
  - transformers
  - mtl
  - monad-control
  - containers
  - bytestring
  - text
  - vector
  - managed
  - linear
  - extra
  - safe

library:
  source-dirs: src
  exposed-modules:
    - Kurokos

executables:
  demo:
    main: Main.hs
    source-dirs: src-demo
    when:
      - condition: flag(demo)
        then:
          dependencies:
            - kurokos
            - kurokos-ui
            - kurokos-asset-raw
            - kurokos-asset-sdl2
            - OpenGL
            - safe-exceptions
            - lens
            - resourcet
        else:
          buildable: False
