name:                kurokos-gfx
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/kurokos-gfx#readme
license:             BSD3
author:              Masato Kobayashi
maintainer:          masatokodo@gmail.com
copyright:           2017 Masato Kobayashi
category:            Graphics
extra-source-files:
- README.md

flags:
  test:
    description: Build testing executable
    manual: False
    default: False

ghc-options:
  - -Wall
  - -fno-warn-unused-do-bind

dependencies:
  - base >= 4.7 && < 5
  - OpenGL
  - OpenGLRaw
  - GLUtil
  - freetype2
  - JuicyPixels
  - JuicyPixels-extra
  - bytestring
  - linear
  - lens
  - vector
  - text

library:
  source-dirs: src
  exposed-modules:
    - Kurokos.Graphics
    - Kurokos.Graphics.Font
    - Kurokos.Graphics.Camera
    - Kurokos.Graphics.Vect
    # Internal
    - Kurokos.Graphics.Types
    - Kurokos.Graphics.Shader

executables:
  test-gfx:
    source-dirs:      src-test
    main:             Main.hs
    when:
      - condition: flag(test)
        then:
          dependencies:
            - kurokos-gfx
            - sdl2 >= 2.2.0
            - linear
            - filepath
            - extra
            - managed
            - binary
        else:
          buildable: False
