name:                kurokos-gfx
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/kurokos-gfx#readme
license:             BSD3
author:              Masato Kobayashi
maintainer:          masatokodo@gmail.com
copyright:           2017 Masato Kobayashi
category:            Graphics
extra-source-files:
- README.md

ghc-options:
  - -Wall
  - -fno-warn-unused-do-bind

dependencies:
  - base >= 4.7 && < 5
  - OpenGL
  - OpenGLRaw
  - GLUtil
  - freetype2
  - JuicyPixels
  - JuicyPixels-extra
  - bytestring
  - linear
  - lens
  - vector
  - text

library:
  source-dirs: src
  exposed-modules:
    - Kurokos.Graphics
    - Kurokos.Graphics.Font
    - Kurokos.Graphics.Camera
# Temporal
    - Kurokos.Graphics.Types
    - Kurokos.Graphics.Texture
    - Kurokos.Graphics.Text
    - Kurokos.Graphics.Shader
    - Kurokos.Graphics.Shader.Basic
    - Kurokos.Graphics.Shader.Text
    - Kurokos.Graphics.Render

executables:
  test-gfx:
    source-dirs:      src-test
    main:             Main.hs
    dependencies:
      - kurokos-gfx
      - sdl2 >= 2.2.0
      - linear
      - filepath
      - extra
      - managed
      - binary
